# Generated by Django 4.2 on 2024-09-16 20:54

import autoslug.fields
import cloudinary.models
import core_apps.profiles.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apartments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "avatar",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="Avatar"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True, verbose_name="Bio")),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("mason", "Mason"),
                            ("carpenter", "Carpenter"),
                            ("plumber", "Plumber"),
                            ("roofer", "Roofer"),
                            ("painter", "Painter"),
                            ("electrician", "Electrician"),
                            ("hvac", "HVAC"),
                            ("tenant", "Tenant"),
                        ],
                        default="tenant",
                        max_length=20,
                        verbose_name="Occupation",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+48507123456",
                        max_length=30,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "country_of_origin",
                    django_countries.fields.CountryField(
                        default="PL", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "city_of_origin",
                    models.CharField(
                        default="Wroclaw", max_length=180, verbose_name="City"
                    ),
                ),
                (
                    "report_count",
                    models.IntegerField(default=0, verbose_name="Report Count"),
                ),
                (
                    "reputation",
                    models.IntegerField(default=100, verbose_name="Reputation"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=core_apps.profiles.models.get_user_username,
                        unique=True,
                    ),
                ),
                (
                    "apartment_profile",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        null=True,
                        verbose_name="Apartment Id",
                    ),
                ),
                ("age", models.PositiveIntegerField(default=0, verbose_name="Age")),
                (
                    "apartments_base_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments_base_profile",
                        to="apartments.apartmentbase",
                        verbose_name="Apartments Profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
