# Generated by Django 4.2 on 2024-09-10 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apartments_base",
                    models.TextField(
                        blank=True, null=True, verbose_name="Apartments BaseJson"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Apartments Base",
            },
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "available",
                    models.CharField(
                        auto_created=True,
                        choices=[("enabled", "enabled"), ("disabled", "disabled")],
                        default="enabled",
                        max_length=12,
                        verbose_name="Available",
                    ),
                ),
                (
                    "apartment_id",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="Apartment Id",
                    ),
                ),
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("building", models.CharField(max_length=50, verbose_name="Building")),
                ("floor", models.PositiveIntegerField(verbose_name="Floor")),
                (
                    "unit_number",
                    models.CharField(max_length=12, verbose_name="Unit Number"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apartment",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["apartment_id"],
            },
        ),
    ]
